### ISSUE TITLE
A few too your splendid work 

### ISSUE THREAD

**Issue by nonso01** [shimul0022/nft-card-challange#1]
Add this few lines to your css file
___
```css
/* hover effect*/
:root{
--trans: all 200ms ease;
--bg_col: hsla(217,54%,11%,1);
--col_gr: hsl(178, 88%, 50%);
--bd: 1px solid currentColor;
}
.main-image{
 border-radius: 9px
}
.main-image:hover{
 background: var(--col_gr) url("/images/icon-view.svg") no-repeat border-box center/15% 15%;
 
}
.main-image:hover img{
 opacity: .2;
 transition: var(--trans);
}
.main-text h2:hover{
 color: var(--col_gr);
}
.creator-div p:hover{
 color: var(--col_gr);
}
hr{
 height: 2px;
 border-radius: 10px;
 background: currentColor;
 border:var(--bd);
}
```
